#!/bin/bash

# EZREC Cron Jobs Setup Script
# Sets up automated maintenance and cleanup tasks

set -e

echo "🔧 Setting up EZREC cron jobs..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    local status=$1
    local message=$2
    case $status in
        "success") echo -e "${GREEN}✅ $message${NC}" ;;
        "error") echo -e "${RED}❌ $message${NC}" ;;
        "warning") echo -e "${YELLOW}⚠️ $message${NC}" ;;
        "info") echo -e "${BLUE}ℹ️ $message${NC}" ;;
    esac
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    print_status "error" "Please run as root (use sudo)"
    exit 1
fi

# EZREC base directory
EZREC_DIR="/opt/ezrec-backend"

# Create cron jobs directory
CRON_DIR="/etc/cron.d"
CRON_FILE="$CRON_DIR/ezrec-maintenance"

echo ""
print_status "info" "Setting up cron jobs in $CRON_FILE"

# Create the cron file
cat > "$CRON_FILE" << 'EOF'
# EZREC Maintenance Cron Jobs
# Generated by setup_cron_jobs.sh

# Daily cleanup at 3 AM
0 3 * * * root /usr/bin/python3 /opt/ezrec-backend/backend/cleanup_old_data.py --recordings-days 7 --logs-days 14 --processed-days 3 --temp-days 1 --cache-days 30 --bookings-days 90 >> /opt/ezrec-backend/logs/cleanup_cron.log 2>&1

# Weekly system health check at 2 AM on Sundays
0 2 * * 0 root /usr/bin/python3 /opt/ezrec-backend/backend/test_system_health.py >> /opt/ezrec-backend/logs/health_check.log 2>&1

# Daily log rotation at 4 AM
0 4 * * * root find /opt/ezrec-backend/logs -name "*.log" -size +100M -exec truncate -s 50M {} \; >> /opt/ezrec-backend/logs/log_rotation.log 2>&1

# Check disk space every 6 hours
0 */6 * * * root df -h /opt/ezrec-backend | awk 'NR==2 {if($5+0 > 90) system("echo \"High disk usage: " $5 " on " $1 "\" | logger -t EZREC")}' >> /opt/ezrec-backend/logs/disk_check.log 2>&1

# Restart services if they're down (every 30 minutes)
*/30 * * * * root /opt/ezrec-backend/restart_services.sh >> /opt/ezrec-backend/logs/service_monitor.log 2>&1

# Backup important configuration files daily at 1 AM
0 1 * * * root tar -czf /opt/ezrec-backend/backups/config_$(date +\%Y\%m\%d).tar.gz -C /opt/ezrec-backend .env api/local_data/ 2>/dev/null || true

# Clean up old backups (keep last 7 days)
0 5 * * * root find /opt/ezrec-backend/backups -name "config_*.tar.gz" -mtime +7 -delete 2>/dev/null || true
EOF

# Set proper permissions
chmod 644 "$CRON_FILE"

print_status "success" "Cron file created: $CRON_FILE"

# Create backups directory
mkdir -p "$EZREC_DIR/backups"
chown root:root "$EZREC_DIR/backups"
chmod 755 "$EZREC_DIR/backups"

print_status "success" "Backups directory created: $EZREC_DIR/backups"

# Create log files with proper permissions
touch "$EZREC_DIR/logs/cleanup_cron.log"
touch "$EZREC_DIR/logs/health_check.log"
touch "$EZREC_DIR/logs/log_rotation.log"
touch "$EZREC_DIR/logs/disk_check.log"
touch "$EZREC_DIR/logs/service_monitor.log"

chown root:root "$EZREC_DIR/logs"/*.log
chmod 644 "$EZREC_DIR/logs"/*.log

print_status "success" "Log files created with proper permissions"

# Test cron job syntax
if crontab -l > /dev/null 2>&1; then
    print_status "info" "Testing cron job syntax..."
    if crontab "$CRON_FILE" 2>/dev/null; then
        print_status "success" "Cron job syntax is valid"
        # Remove the test entry
        crontab -r 2>/dev/null || true
    else
        print_status "error" "Cron job syntax is invalid"
        exit 1
    fi
else
    print_status "warning" "Could not test cron syntax (no existing crontab)"
fi

# Create a simple service monitoring script
cat > "$EZREC_DIR/restart_services.sh" << 'EOF'
#!/bin/bash

# EZREC Service Monitor and Restart Script
# Checks if services are running and restarts them if needed

LOG_FILE="/opt/ezrec-backend/logs/service_monitor.log"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$LOG_FILE"
}

# Check if a service is running
check_service() {
    local service_name=$1
    if ! systemctl is-active --quiet "$service_name"; then
        log "Service $service_name is not running, restarting..."
        systemctl restart "$service_name"
        sleep 5
        if systemctl is-active --quiet "$service_name"; then
            log "Service $service_name restarted successfully"
        else
            log "Failed to restart service $service_name"
        fi
    fi
}

# Check all EZREC services
services=(
    "dual_recorder.service"
    "video_worker.service"
    "system_status.service"
    "log_collector.service"
    "health_api.service"
)

for service in "${services[@]}"; do
    check_service "$service"
done
EOF

chmod +x "$EZREC_DIR/restart_services.sh"
print_status "success" "Service monitoring script created: $EZREC_DIR/restart_services.sh"

# Create a manual cleanup script
cat > "$EZREC_DIR/manual_cleanup.sh" << 'EOF'
#!/bin/bash

# Manual EZREC Cleanup Script
# Run this manually when you need to clean up data

echo "🧹 EZREC Manual Cleanup"
echo "======================"
echo ""

# Check disk usage before cleanup
echo "📊 Disk usage before cleanup:"
df -h /opt/ezrec-backend
echo ""

# Run cleanup with dry-run first
echo "🔍 Running dry-run to see what would be cleaned..."
python3 /opt/ezrec-backend/backend/cleanup_old_data.py --dry-run

echo ""
read -p "Do you want to proceed with actual cleanup? (y/N): " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "🧹 Running actual cleanup..."
    python3 /opt/ezrec-backend/backend/cleanup_old_data.py
    
    echo ""
    echo "📊 Disk usage after cleanup:"
    df -h /opt/ezrec-backend
else
    echo "❌ Cleanup cancelled"
fi
EOF

chmod +x "$EZREC_DIR/manual_cleanup.sh"
print_status "success" "Manual cleanup script created: $EZREC_DIR/manual_cleanup.sh"

# Create a status monitoring script
cat > "$EZREC_DIR/monitor_status.sh" << 'EOF'
#!/bin/bash

# EZREC Status Monitor Script
# Shows current system status and recent activity

echo "📊 EZREC System Status"
echo "======================"
echo ""

# System resources
echo "💻 System Resources:"
echo "CPU Usage: $(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | cut -d'%' -f1)%"
echo "Memory Usage: $(free | grep Mem | awk '{printf("%.1f%%", $3/$2 * 100.0)}')"
echo "Disk Usage: $(df -h /opt/ezrec-backend | awk 'NR==2 {print $5}')"
echo "Temperature: $(vcgencmd measure_temp | cut -d'=' -f2)"
echo ""

# Service status
echo "🔧 Service Status:"
services=(
    "dual_recorder.service"
    "video_worker.service"
    "system_status.service"
    "log_collector.service"
    "health_api.service"
)

for service in "${services[@]}"; do
    if systemctl is-active --quiet "$service"; then
        echo "✅ $service: ACTIVE"
    else
        echo "❌ $service: INACTIVE"
    fi
done
echo ""

# Recent recordings
echo "📹 Recent Recordings:"
find /opt/ezrec-backend/recordings -name "*.mp4" -type f -mtime -1 | head -5 | while read file; do
    size=$(du -h "$file" | cut -f1)
    echo "  $(basename "$file") ($size)"
done
echo ""

# Recent logs
echo "📝 Recent Log Activity:"
tail -5 /opt/ezrec-backend/logs/dual_recorder.log 2>/dev/null | grep -E "(ERROR|WARNING|INFO)" || echo "  No recent log activity"
echo ""

# Network status
echo "🌐 Network Status:"
if ping -c 1 8.8.8.8 >/dev/null 2>&1; then
    echo "✅ Internet: Connected"
else
    echo "❌ Internet: Disconnected"
fi

if curl -s https://api.ezrec.org/status >/dev/null 2>&1; then
    echo "✅ API: Accessible"
else
    echo "❌ API: Not accessible"
fi
echo ""
EOF

chmod +x "$EZREC_DIR/monitor_status.sh"
print_status "success" "Status monitoring script created: $EZREC_DIR/monitor_status.sh"

echo ""
print_status "success" "EZREC cron jobs setup completed!"
echo ""
echo "📋 Installed cron jobs:"
echo "  • Daily cleanup at 3 AM"
echo "  • Weekly health check at 2 AM (Sundays)"
echo "  • Daily log rotation at 4 AM"
echo "  • Disk space check every 6 hours"
echo "  • Service monitoring every 30 minutes"
echo "  • Daily config backup at 1 AM"
echo ""
echo "📁 Created scripts:"
echo "  • $EZREC_DIR/restart_services.sh (Service monitoring)"
echo "  • $EZREC_DIR/manual_cleanup.sh (Manual cleanup)"
echo "  • $EZREC_DIR/monitor_status.sh (Status monitoring)"
echo ""
echo "📊 To monitor cron job activity:"
echo "  tail -f /opt/ezrec-backend/logs/cleanup_cron.log"
echo "  tail -f /opt/ezrec-backend/logs/service_monitor.log"
echo ""
echo "🔧 To run manual cleanup:"
echo "  sudo $EZREC_DIR/manual_cleanup.sh"
echo ""
echo "📊 To check system status:"
echo "  sudo $EZREC_DIR/monitor_status.sh" 